CREATE DATABASE IF NOT EXISTS controlelanche;

USE controlelanche;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CODCLIENTE INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(500) NOT NULL,
    ENDERECO VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CODFUNCIONARIO INT NOT NULL PRIMARY KEY,
    NOMEFUNCIONARIO VARCHAR(500) NOT NULL,
    CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
    ENDERECO_FUNCIONARIO VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDIDO(
	CODPEDIDO INT NOT NULL PRIMARY KEY,
    LOCALPEDIDO VARCHAR(100) NOT NULL,
    DATAPEDIDO DATE NOT NULL,
    
	CODCLIENTE INT NOT NULL,
    CONSTRAINT FK_CLIENTE_PEDIDO
		FOREIGN KEY(CODCLIENTE)
        REFERENCES CLIENTE(CODCLIENTE),
        
	CODFUNCIONARIO INT NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_PEDIDO
		FOREIGN KEY(CODFUNCIONARIO)
        REFERENCES FUNCIONARIO(CODFUNCIONARIO)
);

CREATE TABLE IF NOT EXISTS LANCHE(
	CODLANCHE INT NOT NULL PRIMARY KEY,
    NOMELANCHE VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS INGREDIENTE(
	CODINGREDIENTE INT NOT NULL PRIMARY KEY,
    NOMEINGREDIENTE VARCHAR(300) NOT NULL,
    
    CODLANCHE INT NOT NULL,
    CONSTRAINT FK_LANCHE_INGREDIENTE
		FOREIGN KEY(CODLANCHE)
        REFERENCES LANCHE(CODLANCHE)
);

CREATE TABLE IF NOT EXISTS ITENS(
	CODITENS INT NOT NULL PRIMARY KEY,
    QUANTIDADELANCHE INT NOT NULL,
    
    CODPEDIDO INT NOT NULL,
    CONSTRAINT FK_PEDIDO_ITENS
		FOREIGN KEY(CODPEDIDO)
        REFERENCES PEDIDO(CODPEDIDO),
        
	CODLANCHE INT NOT NULL,
    CONSTRAINT FK_LANCHE_ITENS
		FOREIGN KEY(CODLANCHE)
        REFERENCES LANCHE(CODLANCHE)
);

