CREATE DATABASE IF NOT EXISTS controlehospital;

USE controlehospital;

CREATE TABLE IF NOT EXISTS HOSPITAL(
	CODHOSPITAL INT NOT NULL PRIMARY KEY,
    NOME_HOSPITAL VARCHAR(500) NOT NULL,
    ENDERECO_HOSPITAL VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENFERMEIRO(
	CODENFERMEIRO INT NOT NULL PRIMARY KEY,
    NOME_ENFERMEIRO VARCHAR(500) NOT NULL,
    CPF_ENFERMEIRO VARCHAR(14) NOT NULL,
    RG_ENFERMEIRO VARCHAR(13) NOT NULL,
    DATA_NASCIMENTO_ENFERMEIRO DATE NOT NULL,
    ENDERECO_ENFERMEIRO VARCHAR(300) NOT NULL,
    
    CODHOSPITAL INT NOT NULL,
    CONSTRAINT FK_HOSPITAL_ENFERMEIRO
		FOREIGN KEY(CODHOSPITAL)
        REFERENCES HOSPITAL(CODHOSPITAL)
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CODMEDICO INT NOT NULL PRIMARY KEY,
    NOME_MEDICO VARCHAR(500) NOT NULL,
    CPF_MEDICO VARCHAR(14) NOT NULL,
    RG_MEDICO VARCHAR(13) NOT NULL,
    DATA_NASCIMENTO_MEDICO DATE NOT NULL,
    ENDERECO_MEDICO VARCHAR(300) NOT NULL,
    
    CODHOSPITAL INT NOT NULL,
    CONSTRAINT FK_HOSPITAL_MEDICO
		FOREIGN KEY(CODHOSPITAL)
        REFERENCES HOSPITAL(CODHOSPITAL)
);

CREATE TABLE IF NOT EXISTS PLANO(
	CODPLANO INT NOT NULL PRIMARY KEY,
    VALOR_CONSULTA VARCHAR(500) NOT NULL,
    DATA_CONSULTA DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CODPACIENTE INT NOT NULL PRIMARY KEY,
    NOME_PACIENTE VARCHAR(500) NOT NULL,
    CPF_PACIENTE VARCHAR(14) NOT NULL,
	RG_PACIENTE VARCHAR(13) NOT NULL,
    DATA_NASCIMENTO_PACIENTE DATE NOT NULL,
    ENDERECO_PACIENTE VARCHAR(300) NOT NULL,
    
    CODHOSPITAL INT NOT NULL,
    CONSTRAINT FK_HOSPITAL_PACIENTE
		FOREIGN KEY(CODHOSPITAL)
        REFERENCES HOSPITAL(CODHOSPITAL),
    
    CODPLANO INT NOT NULL,
	CONSTRAINT FK_PLANO_PACIENTE
		FOREIGN KEY(CODPLANO)
        REFERENCES PLANO(CODPLANO)
);

CREATE TABLE IF NOT EXISTS ATENDIMENTO(
	CODATENDIMENTO INT NOT NULL PRIMARY KEY,
    DATA_HORA_ATENDIMENTO DATETIME NOT NULL,
    
    CODPACIENTE INT NOT NULL,
    CONSTRAINT FK_PACIENTE_ATENDIMENTO
		FOREIGN KEY(CODPACIENTE)
        REFERENCES PACIENTE(CODPACIENTE),
        
	CODENFERMEIRO INT NOT NULL,
    CONSTRAINT FK_ENFERMEIRO_ATENDIMENTO
		FOREIGN KEY(CODENFERMEIRO)
        REFERENCES ENFERMEIRO(CODENFERMEIRO),
        
	CODMEDICO INT NOT NULL,
    CONSTRAINT FK_MEDICO_ATENDIMENTO
		FOREIGN KEY(CODMEDICO)
        REFERENCES MEDICO(CODMEDICO)
);

CREATE TABLE IF NOT EXISTS INSUMO(
	CODINSUMO INT NOT NULL PRIMARY KEY,
    TIPO_INSUMO VARCHAR(300) NOT NULL,
    QUANTIDADE_INSUMO INT NOT NULL,
    
    CODATENDIMENTO INT NOT NULL,
    CONSTRAINT FK_ATENDIMENTO_INSUMO
		FOREIGN KEY(CODATENDIMENTO)
        REFERENCES ATENDIMENTO(CODATENDIMENTO)
);
